apiVersion: v1
kind: Service
metadata:
  name: coworking
  labels:
    app: coworking
    app.kubernetes.io/name: coworking
spec:
  type: LoadBalancer
  selector:
    app: coworking
  ports:
    - name: http
      port: 5153
      targetPort: 5153
      protocol: TCP
